version: '2'
services:
    vpay-app:
        image: vpay
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://vpay-mysql:3306/vpay?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://vpay-elasticsearch:9200
        ports:
            - 8080:8080
    vpay-mysql:
        extends:
            file: mysql.yml
            service: vpay-mysql
    vpay-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: vpay-elasticsearch
